# Generated by Django 3.2.6 on 2021-09-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20210906_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseAuthor',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseTag',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseTitle',
            new_name='title',
        ),
    ]
